name: Build examples

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1.16'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y llc
          clang --version
          llc --version

      - name: Build example
        working-directory: examples/programs/kprobe
        run: |
          make build-ebpf
          make build