name: lint
on: [push]
jobs:
  golang-lint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.19.2'
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
