name: lint
on: [push]
jobs:
  golang-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.15.13'
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        skip-go-installation: true
