name: lint
on: [push]
jobs:
  lint:
    name: "lint"
    strategy:
      fail-fast: false
      matrix:
        go: ["1.20", "1.21"]
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
    - name: staticcheck
      uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2022.1.3"
        install-go: false
        cache-key: ${{ matrix.go }}
