name: test
on: [push]
jobs:
  test:
    name: "run tests"
    strategy:
      fail-fast: false
      matrix:
        go: ["1.20", "1.21"]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - run: "sudo go test ./..."
